server:
  port: 8080

spring:
  config:
    activate:
      on-profile:dev
  application:
    name: SelfCourier
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect

imagekit:
  publicKey: ${imageKit_PUBLIC_KEY}
  privateKey: ${imageKit_PRIVATE_KEY}
  urlEndpoint: ${imageKit_URL_ENDPOINT}
  tokenImageKitAuthUUID: ${tokenImageKitAuthUUID}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}